name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: npm ci

      - name: Formation and linting
        run: |
          npm run lint
          npm run stylelint
          npm run tsc:check

      - name: Testing
        run: npm run test

      # - name: Publish
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=site --functions=functions
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
